
name: 'Push News'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *' # 定义 cron 表达式
  watch:
    types: [started] # 定义star是自动发送

  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: '开始运行'
      run: python ithome.py   
  
